//   SleepStressView.swift
//   BigPlan
//
//   Created by: Gp. on 5/5/25 at 7:38 PM
//     Modified:
//
//  Copyright Delicious Studios, LLC. - Grant Perry
//

import SwiftUI

struct SleepStressView: View {
   @ObservedObject var bigPlanViewModel: BigPlanViewModel
   @State private var sleepHoursString: String = ""
   @State private var sleepMinutesString: String = ""

   var body: some View {
	  VStack(alignment: .leading, spacing: 20) {
		 Text("SLEEP & STRESS")
			.font(.subheadline)
			.foregroundColor(.gray)

		 VStack(spacing: 16) {
			HStack {
			   Text("Sleep Time")
			   Spacer()
			   TextField("H", text: $sleepHoursString)
				  .keyboardType(.numberPad)
				  .multilineTextAlignment(.trailing)
				  .frame(width: 40)
				  .onChange(of: sleepHoursString) { _, newValue in
					 if let hours = Int(newValue), hours > 24 {
						sleepHoursString = "24"
					 }
					 if newValue.count > 2 {
						sleepHoursString = String(newValue.prefix(2))
					 }
				  }
			   Text(":")
			   TextField("M", text: $sleepMinutesString)
				  .keyboardType(.numberPad)
				  .multilineTextAlignment(.trailing)
				  .frame(width: 40)
				  .onChange(of: sleepMinutesString) { _, newValue in
					 if let minutes = Int(newValue), minutes > 59 {
						sleepMinutesString = "59"
					 }
					 if newValue.count > 2 {
						sleepMinutesString = String(newValue.prefix(2))
					 }
				  }
			}
			Divider()

			HStack {
			   Text("Stress Level")
			   Spacer()
			   Picker("", selection: Binding(
				  get: {
					 switch bigPlanViewModel.stressLevel {
						case 1: return "Low"
						case 2: return "Medium"
						case 3: return "High"
						default: return ""
					 }
				  },
				  set: { newValue in
					 switch newValue {
						case "Low": bigPlanViewModel.stressLevel = 1
						case "Medium": bigPlanViewModel.stressLevel = 2
						case "High": bigPlanViewModel.stressLevel = 3
						default: bigPlanViewModel.stressLevel = nil
					 }
				  }
			   )) {
				  Text("").tag("")
				  Text("Low").tag("Low")
				  Text("Medium").tag("Medium")
				  Text("High").tag("High")
			   }
			   .labelsHidden()
			}
		 }
		 .padding()
		 .background(Color(.secondarySystemBackground))
		 .cornerRadius(10)
	  }
	  .onChange(of: sleepHoursString) { _, _ in updateViewModelSleepTime() }
	  .onChange(of: sleepMinutesString) { _, _ in updateViewModelSleepTime() }
	  .onChange(of: bigPlanViewModel.sleepTime) { _, _ in
		 updateLocalSleepStrings()
	  }
	  .onAppear {
		 updateLocalSleepStrings()
	  }
   }

   private func updateViewModelSleepTime() {
	  if sleepHoursString.isEmpty && sleepMinutesString.isEmpty {
		 bigPlanViewModel.sleepTime = nil
		 return
	  }

	  let hours = Int(sleepHoursString) ?? 0
	  let minutes = Int(sleepMinutesString) ?? 0

	  // Validate hours and minutes
	  // Allow hours up to 24 (e.g., for total sleep in a day rather than clock time)
	  guard hours >= 0, hours <= 24, minutes >= 0, minutes <= 59 else {
		 // If validation fails, consider clearing or not updating,
		 // or provide user feedback. For now, let's prevent bad data.
		 // bigPlanViewModel.sleepTime = nil // or some other handling
		 return
	  }

	  // Format the time string
	  // Ensure minutes are always two digits
	  let formattedTime = "\(hours):\(String(format: "%02d", minutes))"
	  if bigPlanViewModel.sleepTime != formattedTime {
		 bigPlanViewModel.sleepTime = formattedTime
	  }
   }

   private func updateLocalSleepStrings() {
	  // Only update if the ViewModel's value is different from what would be generated by current local strings
	  let currentLocalFormattedTime: String?
	  if sleepHoursString.isEmpty && sleepMinutesString.isEmpty {
		 currentLocalFormattedTime = nil
	  } else {
		 let h = Int(sleepHoursString) ?? 0
		 let m = Int(sleepMinutesString) ?? 0
		 currentLocalFormattedTime = "\(h):\(String(format: "%02d", m))"
	  }

	  if bigPlanViewModel.sleepTime == currentLocalFormattedTime {
		 return // No change needed, prevents potential loops
	  }

	  guard let timeString = bigPlanViewModel.sleepTime else {
		 sleepHoursString = ""
		 sleepMinutesString = ""
		 return
	  }

	  let components = timeString.split(separator: ":").map(String.init)
	  if components.count == 2 {
		 sleepHoursString = components[0]
		 // Ensure minutes string from view model correctly pads if it was stored like "8:5"
		 if let minInt = Int(components[1]) {
			sleepMinutesString = String(format: "%02d", minInt)
		 } else {
			sleepMinutesString = components[1] // Fallback if not an int
		 }

	  } else {
		 // If format is unexpected, clear local strings
		 sleepHoursString = ""
		 sleepMinutesString = ""
	  }
   }
}
